<?php

/*
 * @author Max Severin <makc.severin@gmail.com>
 */
return array(
    'status' => array(
        'title'        => _wp('Status'),
        'value'        => 'off',
        'control_type' => waHtmlControl::SELECT,
        'options'      => array(
            'off' => _wp('Off'),
            'on'  => _wp('On'),
        ),
    ),
    'comment_status' => array(
        'title'        => _wp('Comment'),
        'description'  => _wp('The opportunity to leave a comment.'),
        'value'        => 'off',
        'control_type' => waHtmlControl::SELECT,
        'options'      => array(
            'off' => _wp('Off'),
            'on'  => _wp('On'),
        ),
    ),
    'id_in_html' => array(
        'title'        => _wp('Selector of the button of fast order'),
        'description'  => _wp('Specify the ID or class of the html element,<br />when clicking on which will open a form of fast order.<br />Must be like «<b>#fast-order-button</b>» or «<b>.fast-order-button</b>».'),
        'placeholder'  => '#fast-order-button',
        'value'        => '#fast-order-button',
        'control_type' => waHtmlControl::INPUT,
    ),
    'phone_masked_input' => array(
        'title'        => _wp('Masked input for phone'),
        'description'  => _wp('If fill this setting will added the mask for the field with the phone number.<br />Tip about masks characters:<br /><b>a</b> - All alphabetic values (A-Z, a-z)<br /><b>9</b> - All numeric values (0-9)<br /><b>*</b> - Any alphanumeric values (A-Z, a-z, 0-9).<br />Leave the field empty, if you do not need mask input.'),
        'placeholder'  => '+7 (999) 999-99-99',
        'value'        => '',
        'control_type' => waHtmlControl::INPUT,
    ),
    'text_header_title' => array(
        'title'        => _wp('Header text'),
        'placeholder'  => _wp('Fast order'),
        'value'        => _wp('Fast order'),
        'control_type' => waHtmlControl::INPUT,
    ),
    'text_name_placeholder' => array(
        'title'        => _wp('«Name» field placeholder'),
        'placeholder'  => _wp('Your Name'),
        'value'        => _wp('Your Name'),
        'control_type' => waHtmlControl::INPUT,
    ),
    'text_phone_placeholder' => array(
        'title'        => _wp('«Phone» field placeholder'),
        'placeholder'  => _wp('Your Phone'),
        'value'        => _wp('Your Phone'),
        'control_type' => waHtmlControl::INPUT,
    ),
    'text_email_placeholder' => array(
        'title'        => _wp('«Email» field placeholder'),
        'placeholder'  => _wp('Your Email'),
        'value'        => _wp('Your Email'),
        'control_type' => waHtmlControl::INPUT,
    ),
    'text_comment_placeholder' => array(
        'title'        => _wp('«Comment» field placeholder'),
        'placeholder'  => _wp('Your comment'),
        'value'        => _wp('Your comment'),
        'control_type' => waHtmlControl::INPUT,
    ),
    'text_submit_button' => array(
        'title'        => _wp('«Buy» button text'),
        'placeholder'  => _wp('Buy'),
        'value'        => _wp('Buy'),
        'control_type' => waHtmlControl::INPUT,
    ),
    'style_form_width' => array(
        'title'        => _wp('Form width (px)'),
        'description'  => _wp('Value range 320-600'),
        'placeholder'  => '400',
        'value'        => '400',
        'control_type' => waHtmlControl::CUSTOM.' '.'shopForderPlugin::settingNumberControl',
        'options'      => array(
            'min'  => '320',
            'max'  => '600',
            'step' => '1',
        ),
    ),
    'style_form_height' => array(
        'title'        => _wp('Form height (px)'),
        'description'  => _wp('Value range 240-480'),
        'placeholder'  => '340',
        'value'        => '340',
        'control_type' => waHtmlControl::CUSTOM.' '.'shopForderPlugin::settingNumberControl',
        'options'      => array(
            'min'  => '240',
            'max'  => '480',
            'step' => '1',
        ),
    ),
    'style_form_background' => array(
        'title'        => _wp('Form background color (HEX)'),
        'class'        => 's-color',
        'placeholder'  => 'ffffff',
        'value'        => 'ffffff',
        'control_type' => waHtmlControl::CUSTOM.' '.'shopForderPlugin::settingColorControl',
    ),
    'style_header_background' => array(
        'title'        => _wp('Header background color (HEX)'),
        'class'        => 's-color',
        'placeholder'  => '21a6de',
        'value'        => '21a6de',
        'control_type' => waHtmlControl::CUSTOM.' '.'shopForderPlugin::settingColorControl',
    ),
    'style_header_text_color' => array(
        'title'        => _wp('Header text color (HEX)'),
        'class'        => 's-color',
        'placeholder'  => 'ffffff',
        'value'        => 'ffffff',
        'control_type' => waHtmlControl::CUSTOM.' '.'shopForderPlugin::settingColorControl',
    ),
    'style_submit_width' => array(
        'title'        => _wp('«Buy» button width (px)'),
        'description'  => _wp('Value range 100-600'),
        'placeholder'  => '300',
        'value'        => '300',
        'control_type' => waHtmlControl::CUSTOM.' '.'shopForderPlugin::settingNumberControl',
        'options'      => array(
            'min'  => '100',
            'max'  => '600',
            'step' => '1',
        ),
    ),
    'style_submit_height' => array(
        'title'        => _wp('«Buy» button height (px)'),
        'description'  => _wp('Value range 24-160'),
        'placeholder'  => '34',
        'value'        => '34',
        'control_type' => waHtmlControl::CUSTOM.' '.'shopForderPlugin::settingNumberControl',
        'options'      => array(
            'min'  => '24',
            'max'  => '160',
            'step' => '1',
        ),
    ),
    'style_submit_background' => array(
        'title'        => _wp('«Buy» button background color (HEX)'),
        'class'        => 's-color',
        'placeholder'  => '21a6de',
        'value'        => '21a6de',
        'control_type' => waHtmlControl::CUSTOM.' '.'shopForderPlugin::settingColorControl',
    ),
    'style_submit_text_color' => array(
        'title'        => _wp('«Buy» button text color (HEX)'),
        'class'        => 's-color',
        'placeholder'  => 'ffffff',
        'value'        => 'ffffff',
        'control_type' => waHtmlControl::CUSTOM.' '.'shopForderPlugin::settingColorControl',
    ),
    'style_close_ok_background' => array(
        'title'        => _wp('«Close» button background color when sending is success (HEX)'),
        'class'        => 's-color',
        'placeholder'  => '4d9b58',
        'value'        => '4d9b58',
        'control_type' => waHtmlControl::CUSTOM.' '.'shopForderPlugin::settingColorControl',
    ),
    'style_close_error_background' => array(
        'title'        => _wp('«Close» button background color when error occurred (HEX)'),
        'class'        => 's-color',
        'placeholder'  => 'de4d2c',
        'value'        => 'de4d2c',
        'control_type' => waHtmlControl::CUSTOM.' '.'shopForderPlugin::settingColorControl',
    ),
    'text_thanks_message' => array(
        'title'        => _wp('«Thanks message» text (appeal)'),
        'placeholder'  => _wp('Thanks') . ',',
        'value'        => _wp('Thanks') . ',',
        'control_type' => waHtmlControl::INPUT,
    ),
    'text_more_thanks_message' => array(
        'title'        => _wp('«Thanks message» text (text in 2nd line)'),
        'placeholder'  => _wp('your order is placed!'),
        'value'        => _wp('your order is placed!'),
        'control_type' => waHtmlControl::INPUT,
    ),
    'style_thanks_text_color' => array(
        'title'        => _wp('«Thanks message» text color'),
        'class'        => 's-color',
        'placeholder'  => '717171',
        'value'        => '717171',
        'control_type' => waHtmlControl::CUSTOM.' '.'shopForderPlugin::settingColorControl',
    ),
);